project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Yuchao Guo"
  site-url: https://guo-yu-chao.github.io
  favicon: images/site-logo.png
  repo-url: https://github.com/guo-yu-chao/guo-yu-chao.github.io
  repo-actions: [edit, issue]
  
  page-footer:
    left: |
     
    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#00CCCC"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Blogs"
        href: blog.qmd
      - text: "CV"
        href: Yuchao Guo_CV.pdf

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细